name: Copy Book To VE Org

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}

    - name: Copies book PDF to VE.org
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.book_copy }}
      with:
        source_file: 'concept_primer/_main.pdf'
        destination_repo: 'VisionEval/VisionEval.org'
        destination_folder: 'book'
        user_email: 'daniel.flynn@dot.gov'
        user_name: 'dflynn-volpe'
        